"use client"
import { Inter } from "next/font/google";
import "./css/acss/acss.css";
import "./css/bootstrap-5/css/bootstrap.css";
import "./css/fontawesome/css/all.min.css";
import "./globals.css";
import {PlayerContextProvider,Player,Menu,SearchBar} from "./component.js";
import Link from "next/link"
import React from "react"
import {usePathname} from "next/navigation"

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const path = usePathname()
  const [showMenu , setShowMenu] = React.useState()

  React.useEffect(()=>{
    setShowMenu()
  },[path])

  return (
    <html lang="en">
      <body className="font-montserrat color-bg-p">
      
      <PlayerContextProvider>
      <header class=" color-p sz-14 container-fluid color-bg-t sticky-top" style={{maginRight:'-2px'}}>
      <div class="row p-2 sz-16 bold py-3">
        <div class="col font-slick">
           <span class=""> audioflix </span> 
        </div>
        <div  class="col d-md-none right">
          <Link class="cursor d-none color-t-hover sz-16 no-decoration color-black" style={{cursor:'pointer'}} href="/search"><i class="fas fa-search"></i>  </Link>
          <i class="fas fa-bars sz-24" onClick={()=>setShowMenu((prev)=>!prev)}></i>
        </div>
      </div>
      </header>

      <div class="container-fluid">
        <div class="row">
          <div class="col">
            <div class="row gx-md-5">


              <div class={`col-2 ${!showMenu && "d-none d-md-none"} d-lg-block p-0 m-0`} style={{backgroundColor:"#F5D0D0",height:"100vh"}}>
                              <div class="position-fixed m-0 container col-md-2" style={{backgroundColor:"#F5D0D0",height:"100vh",}} >
                                
                                <div class="gy-4  row p-3 sz-16 color-black" >
                                  <div class="col-12 center pr-3 font-great hide">
                                    Audio flix
                                  </div>
                                </div>
                  
              
                                <div class="row">
                                  <div class="col-12 p-4"> 
                                    <Link class="cursor color-t-hover sz-16 no-decoration color-black" style={{cursor:'pointer'}} href="/music"><i class="fas fa-home rounded p-2 color-white color-bg-t sz-14 mx-2"></i> Home</Link> 
                                    </div>
                                  </div>
              
                                <div class="row">
                                  <div class="col-12 p-4"> 
                                    <Link class="cursor color-t-hover sz-16 no-decoration color-black" style={{cursor:'pointer'}} href="/search"><i class="fas fa-search rounded p-2 color-white color-bg-t sz-14 mx-2"></i> Search Music </Link>
                                  </div>
                                </div>
              
                                  <div class="row">
                                  <div class="col-12 p-4"> 
                                    <Link class="cursor color-t-hover sz-16 no-decoration color-black" style={{cursor:'pointer'}} href="/history"><i class="fas fa-music rounded p-2 color-white color-bg-t sz-14 mx-2"></i> Playing History</Link>
                                  </div>
                                </div>
              
                              </div>
                            </div>

              <div class="col">
                {children}
              </div>
            </div>
          </div>
        </div>
      </div>
      
      {/*showSearch && <div class="row position-absolute py-3 w-100 m-1 d-md-none">
              <div class="col"> <SearchBar className="col-12 w-100 py-3" /> </div>
            </div>*/}
      
      <br />
      <br />
      <br />
      <br class="d-md-block d-none" />
      <br class="d-md-block d-none" />
      <div id="fixed-bottom" class="fixed-bottom" style={{bottom:'0px'}} >
      
      <Player />
      </div>
      
      </PlayerContextProvider>
      </body>
    </html>
  );
}


