import { Inter } from "next/font/google";
import "./css/acss/acss.css";
import "./css/bootstrap-5/css/bootstrap.css";
import "./css/fontawesome/css/all.min.css";
import "./globals.css";
import {PlayerContextProvider,Player,Menu} from "./component.js";
import Link from "next/link"

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="font-poppins color-bg-p container-fluid p-0">
      <header class="color-bg-t color-p sz-14 container-fluid">
      <div class="row p-3 sz-18">
        <div class="col ">
          AudioFlix
        </div>
        <div class="col right">
          <Menu />
        </div>
      </div>
      </header>

      <PlayerContextProvider>
      {children}
      <div id="fixed-bottom" class="fixed-bottom" style={{bottom:'0px',overflow:'hidden'}} >
      <Player />
      </div>
      </PlayerContextProvider>
      </body>
    </html>
  );
}


