import { Inter } from "next/font/google";
import "./css/acss/acss.css";
import "./css/bootstrap-5/css/bootstrap.css";
import "./css/fontawesome/css/all.min.css";
import "./globals.css";
import {PlayerContextProvider,Player,Menu} from "./component.js";
import Link from "next/link"

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="font-montserrat color-bg-p">
      
      <PlayerContextProvider>
      {children}
      
      <br />
      <br />
      <br />
      <br class="d-md-block d-none" />
      <br class="d-md-block d-none" />
      <div id="fixed-bottom" class="fixed-bottom" style={{bottom:'0px'}} >
      
      <Player />
      </div>
      
      </PlayerContextProvider>
      </body>
    </html>
  );
}


